services:
  postgres:
    image: postgres:16
    container_name: desafio-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: desafio_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: