services:
  postgres:
    image: postgres:16
    container_name: desafio-postgres
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: desafiodb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      device: C:/Desafio Paschoaloto/Desafio/db
      o: bind
