// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Parcela", b =>
                {
                    b.Property<string>("TituloNumero")
                        .HasColumnType("text");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("Vencimento")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TituloNumero", "NumeroParcela");

                    b.ToTable("Parcelas", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Titulo", b =>
                {
                    b.Property<string>("Numero")
                        .HasColumnType("text");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("JurosMensal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MultaPercentual")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("NomeDevedor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Numero");

                    b.ToTable("Titulos", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Parcela", b =>
                {
                    b.HasOne("Domain.Entities.Titulo", "Titulo")
                        .WithMany("Parcelas")
                        .HasForeignKey("TituloNumero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Titulo");
                });

            modelBuilder.Entity("Domain.Entities.Titulo", b =>
                {
                    b.Navigation("Parcelas");
                });
#pragma warning restore 612, 618
        }
    }
}
